name: Node.js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Updated CHANGELOG.md
        run: >-
          if [[ "$GITHUB_REF" != 'refs/heads/master' && "$GITHUB_REF" != *'dependabot'* ]]; then
            ! diff CHANGELOG.md <(curl -s "https://raw.githubusercontent.com/hms-dbmi/viv/master/CHANGELOG.md")
          fi

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build Avivator
        run: pnpm --filter=avivator build

  test-linux:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Check formatting
        run: pnpm check-format

      - name: Lint
        run: pnpm lint

      - name: Setup xvf (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Test
        run: pnpm test

      - name: Build avivator
        run: pnpm --filter=avivator build

  publish:
    needs: [check-changelog, build-windows, test-linux]
    runs-on: ubuntu-latest
    # this will run when you have tagged a commit, starting with "v*"
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --filter='./packages/*' --dry-run

      - name: Build Avivator & Documentation
        run: pnpm build

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.VIV_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.VIV_S3_ACCESS_KEY_SECRET }}
        run: |
          aws s3 cp --recursive sites/avivator/dist s3://avivator.gehlenborglab.org --dry-run
          aws s3 cp --recursive sites/docs/dist s3://viv.gehlenborglab.org --dry-run

