name: Node.js CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"

  pull_request:
    branches:
      - master

jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Updated CHANGELOG.md
        env:
          REF: ${{ github.ref }}
        if: github.ref != 'refs/heads/master' && !contains(github.ref, 'dependabot') && !contains(github.ref, 'tags')
        run: |
          echo '${{ env.REF }}'
          ! diff CHANGELOG.md <(curl -s "https://raw.githubusercontent.com/hms-dbmi/viv/master/CHANGELOG.md")

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build Avivator
        run: pnpm --filter=avivator build

  test-linux:
    runs-on: ubuntu-20.04
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Check formatting
        run: pnpm check-format

      - name: Lint
        run: pnpm lint

      - name: Setup xvf (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Test
        run: pnpm test

      - name: Build packages and sites
        run: pnpm build

  publish:
    needs: [check-changelog, build-windows, test-linux]
    runs-on: ubuntu-latest
    # this will run when you have tagged a commit, starting with "v*"
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build packages and sites
        run: pnpm build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --filter='./packages/*' --no-git-checks

      - name: Upload to S3
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.VIV_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.VIV_S3_ACCESS_KEY_SECRET }}
        run: |
          aws s3 cp --recursive sites/avivator/dist s3://avivator.gehlenborglab.org
          aws s3 cp --recursive sites/docs/dist s3://viv.gehlenborglab.org
          aws cloudfront create-invalidation --distribution-id  E204VEQ9XF37EF --paths "/*"
